# -*- coding: utf-8 -*-
"""Untitled178.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADraUeFm41HUdEHMxzzd99du9I9-NTUD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df= pd.read_csv("/content/salary.csv")

df.head()

df.isnull().sum()

x=df.iloc[:,:-1]
y=df["subscription"]
x.columns

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)



from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
original_columns = x.columns # Store column names before transformation
x_=sc.fit_transform(x)


x = pd.DataFrame(x_,columns=original_columns)
x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
data =dt.fit(x_train,y_train)

(data.score(x_test,y_test) )*100

data.predict([[39	,34000		]])

from sklearn.tree import plot_tree
plot_tree(data)





